# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzTi2EJYGJpg712yMOTaUCsVswhzJ9jC
"""

import numpy as np

A = np.array([[1,3,-2,0,2,0,0],[2,6,-5,-2,4,-3,0],[0,0,5,10,0,15,0],[2,6,0,8,4,18,0]])
A

def escalonamento(matriz, m, n):
  coluna=0
  #Auxiliar para achar o pivo
  pivo=0
  
  while(coluna<n):
    if (matriz[[pivo],[coluna]]!=0):
      matriz[[pivo]] = matriz[[pivo]]*(1/(matriz[[pivo],[coluna]]))
      i=0
      while(i<m):
        if (i==pivo):
          i=i+1
        else:
          matriz[[i]] = matriz[[i]] + matriz[[pivo]]*(matriz[[i],[coluna]]*-1)
          i=i+1
      print(f"Coluna {coluna} alterada")
      print(f"{matriz}")
      pivo=pivo+1
      coluna=coluna+1
    else:
      print(f"Coluna {coluna} pulada")
      coluna=coluna+1

escalonamento(A, 4 ,6)

B=A
B

B[[1]] = B[[1]] + B[[0]]*(B[[1],[0]]*-1)
B[[3]] = B[[3]] + B[[0]]*(B[[3],[0]]*-1)
B

B[[1]] = B[[1]]*(1/(B[[1],[2]]))
B

B[[0]] = B[[0]] + B[[1]]*(B[[0],[2]]*-1)
B[[2]] = B[[2]] + B[[1]]*(B[[2],[2]]*-1)
B[[3]] = B[[3]] + B[[1]]*(B[[3],[2]]*-1)
B